[build]
  functions = "functions"
  publish = "templates"
  command = "pip install -r requirements.txt"

[functions]
  included_files = ["app.py", "templates/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200